// Code generated by go-swagger; DO NOT EDIT.

package price

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetPriceParams creates a new GetPriceParams object
// no default values defined in spec.
func NewGetPriceParams() GetPriceParams {

	return GetPriceParams{}
}

// GetPriceParams contains all the bound params for the get price operation
// typically these are obtained from a http.Request
//
// swagger:parameters getPrice
type GetPriceParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Target coin symbol
	  In: query
	*/
	Convert *string
	/*Source coin symbol
	  In: query
	*/
	Symbol *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetPriceParams() beforehand.
func (o *GetPriceParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qConvert, qhkConvert, _ := qs.GetOK("convert")
	if err := o.bindConvert(qConvert, qhkConvert, route.Formats); err != nil {
		res = append(res, err)
	}

	qSymbol, qhkSymbol, _ := qs.GetOK("symbol")
	if err := o.bindSymbol(qSymbol, qhkSymbol, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindConvert binds and validates parameter Convert from query.
func (o *GetPriceParams) bindConvert(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.Convert = &raw

	return nil
}

// bindSymbol binds and validates parameter Symbol from query.
func (o *GetPriceParams) bindSymbol(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.Symbol = &raw

	return nil
}
