// Code generated by go-swagger; DO NOT EDIT.

package price

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetPriceOKCode is the HTTP code returned for type GetPriceOK
const GetPriceOKCode int = 200

/*GetPriceOK login

swagger:response getPriceOK
*/
type GetPriceOK struct {

	/*
	  In: Body
	*/
	Payload *GetPriceOKBody `json:"body,omitempty"`
}

// NewGetPriceOK creates GetPriceOK with default headers values
func NewGetPriceOK() *GetPriceOK {

	return &GetPriceOK{}
}

// WithPayload adds the payload to the get price o k response
func (o *GetPriceOK) WithPayload(payload *GetPriceOKBody) *GetPriceOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get price o k response
func (o *GetPriceOK) SetPayload(payload *GetPriceOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPriceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
