swagger: '2.0'
info:
  description: This is the api POC
  version: 0.1.0
  title: Go server price API
host: api.price.com
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
tags:
  - name: price
    description: Price random generator

paths:
  /*:
    options:
      operationId: optionsAllow
      security: []
      produces:
        - application/json
      responses:
        '200':
          description: Successful operation
  /price:
    get:
      tags:
        - price
      summary: Get price
      description: Get a random price
      operationId: getPrice
      parameters:
        - in: query
          name: symbol
          type: string
          description: Source coin symbol
        - in: query
          name: convert
          type: string
          description: Target coin symbol
      responses:
        '200':
          description: login
          schema:
            properties:
              price:
                type: number
                format: float

