// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Go server price API
This is the api POC


    Schemes:
      http
    Host: api.price.com
    BasePath: /v1
    Version: 0.1.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
