// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "This is the api POC",
    "title": "Go server price API",
    "version": "0.1.0"
  },
  "host": "api.price.com",
  "basePath": "/v1",
  "paths": {
    "/*": {
      "options": {
        "security": [],
        "produces": [
          "application/json"
        ],
        "operationId": "optionsAllow",
        "responses": {
          "200": {
            "description": "Successful operation"
          }
        }
      }
    },
    "/price": {
      "get": {
        "description": "Get a random price",
        "tags": [
          "price"
        ],
        "summary": "Get price",
        "operationId": "getPrice",
        "parameters": [
          {
            "type": "string",
            "description": "Source coin symbol",
            "name": "symbol",
            "in": "query"
          },
          {
            "type": "string",
            "description": "Target coin symbol",
            "name": "convert",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "login",
            "schema": {
              "properties": {
                "price": {
                  "type": "number",
                  "format": "float"
                }
              }
            }
          }
        }
      }
    }
  },
  "tags": [
    {
      "description": "Price random generator",
      "name": "price"
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "This is the api POC",
    "title": "Go server price API",
    "version": "0.1.0"
  },
  "host": "api.price.com",
  "basePath": "/v1",
  "paths": {
    "/*": {
      "options": {
        "security": [],
        "produces": [
          "application/json"
        ],
        "operationId": "optionsAllow",
        "responses": {
          "200": {
            "description": "Successful operation"
          }
        }
      }
    },
    "/price": {
      "get": {
        "description": "Get a random price",
        "tags": [
          "price"
        ],
        "summary": "Get price",
        "operationId": "getPrice",
        "parameters": [
          {
            "type": "string",
            "description": "Source coin symbol",
            "name": "symbol",
            "in": "query"
          },
          {
            "type": "string",
            "description": "Target coin symbol",
            "name": "convert",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "login",
            "schema": {
              "properties": {
                "price": {
                  "type": "number",
                  "format": "float"
                }
              }
            }
          }
        }
      }
    }
  },
  "tags": [
    {
      "description": "Price random generator",
      "name": "price"
    }
  ]
}`))
}
